codecov:
  notify:
    after_n_builds: 7

comment:
  require_changes: true
  layout: "diff, files"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch: off

fixes:
  - "nc_py_api/::"
