blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/cloud-py-api/nc_py_api/discussions/new
    about: Ask questions and discuss
  - name: Blank issue
    url: https://github.com/cloud-py-api/nc_py_api/issues/new
    about: Please note that Github Discussions should be used in most cases instead
