name: Analysis & Coverage (Unrelated)

on:
  pull_request:
    paths-ignore:
      - '.github/workflows/analysis-coverage.yml'
      - 'nc_py_api/*.*'
      - 'tests/**'
      - 'setup.*'
      - 'pyproject.toml'
      - '.pre-commit-config.yaml'

permissions:
  contents: read

concurrency:
  group: ana_cov-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests-success:
    permissions:
      contents: none
    runs-on: ubuntu-22.04
    name: Tests-OK
    steps:
      - run: echo "No Tests required"
