name: Docs check
on:
  pull_request:

permissions:
  contents: read

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Docs dependencies
        run: python3 -m pip install ".[docs]"

      - name: Build and push Docs
        run: |
          make html SPHINXOPTS="-W"
